<?php declare(strict_types=1);
/**
 * Copyright © 2023-present ParadoxLabs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Need help? Try our knowledgebase and support system:
 *
 * @link https://support.paradoxlabs.com
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\PaymentIcons\ViewModel\PaymentIconsDark;
use Magento\Framework\Escaper;
use ParadoxLabs\AuthnetcimHyvaCheckout\Block\CheckoutTemplate;
use ParadoxLabs\AuthnetcimHyvaCheckout\Magewire\Payment\Authnetcim;
use ParadoxLabs\AuthnetcimHyvaCheckout\ViewModel\PaymentForm;

/** @var CheckoutTemplate $block */
/** @var Authnetcim $magewire */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var PaymentForm $formViewModel */
/** @var \Hyva\PaymentIcons\ViewModel\PaymentIconsDark $paymentIcons */

$code           = $escaper->escapeHtmlAttr($block->getData('method_code'));
$formViewModel  = $viewModels->require(PaymentForm::class);
$formBlock      = $formViewModel->getFormBlock($code);
$method         = $formBlock->getMethod();
$image          = $formBlock->getBrandingImage();
$paymentIcons   = $viewModels->require(PaymentIconsDark::class);

$typeIconMap = [
    'AE' => 'americanExpress',
    'DC' => 'dinersClub',
    'DI' => 'discover',
    'JCB' => 'jcb',
    'MC' => 'mastercard',
    'VI' => 'visa',
    'UN' => 'unionpay',
    'OT' => 'creditcard',
];
?>
<div class="<?= $code ?>"
     x-data="<?= $code ?>PaymentForm"
     x-init="initForm"
     data-config='<?= $escaper->escapeJsQuote(json_encode($block->getConfig())) ?>'
>
    <?php if ($image): ?>
        <div class="flex justify-end mb-2">
            <img src="<?= $escaper->escapeUrl($image); ?>" alt="<?= $escaper->escapeHtmlAttr($method->getTitle()) ?>" />
        </div>
    <?php endif; ?>

    <div class="field required mb-2" x-show="showStoredCards" x-cloak>
        <label for="<?= $code ?>-card-id" class="label text-gray-700 text-sm">
            <?= $escaper->escapeHtml(__('Payment Information')) ?>
        </label>
        <select id="<?= $code ?>-card-id"
                class="block w-full shadow-sm border-gray-300 rounded-md"
                :value="selectedCard"
                @change="setSelectedCard"
        >
            <template x-for="storedCard in storedCards" :key="storedCard.hash">
                <option :value="storedCard.hash"
                        :data-type="storedCard.type"
                        :selected="isStoredCardSelected"
                        x-text="storedCard.label">
                </option>
            </template>
            <option value=''><?= $escaper->escapeHtml(__('Add new card')) ?></option>
        </select>

        <?php if ($magewire->hasError('selectedCard')): ?>
            <span class="text-red-800" id="selected-card-error">
                <?= $escaper->escapeHtml($magewire->getError('selectedCard')) ?>
            </span>
        <?php endif ?>
    </div>

    <div class="card prose -m-4 mt-0 sm:m-0 grid gap-4"
         x-show="showForm"
         wire:ignore
    >
        <div class="field required">
            <label for="<?= $code ?>-cc-number" class="label text-gray-700 text-sm">
                <?= $escaper->escapeHtml(__('Card Number')) ?>
            </label>
            <div class="relative">
                <input type="text"
                       inputmode="numeric"
                       title="<?= $escaper->escapeHtmlAttr(__('Card Number')) ?>"
                       class="block w-full shadow-sm border-gray-300 rounded-md font-mono leading-normal tracking-wider transition"
                       id="<?= $code ?>-cc-number"
                       :value="payment.cc_number"
                       @keyup="formatCreditCard"
                       @change="validateCcNumber"
                       value=""
                       autocomplete="cc-number"
                       placeholder="0000 0000 0000 0000"
                       spellcheck="false"
                       minlength="13"
                       maxlength="24"
                       required
                />
                <div class="absolute top-0 right-0 p-1 pointer-events-none"
                     x-show="showCcType"
                     x-cloak
                >
                    <?php foreach($formBlock->getCcAvailableTypes() + ['OT' => 'Credit Card'] as $type => $label): ?>
                        <?php if (!isset($typeIconMap[$type])) {continue;} ?>
                        <?php $icon = $typeIconMap[$type] . 'Html'; ?>
                        <?= $paymentIcons->{$icon}('', 48, 32, ["aria-label" => $label, 'data-type' => $escaper->escapeHtmlAttr($type), 'x-show' => 'isCcTypeActive']) ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="grid grid-cols-2 gap-2">
            <div class="field required">
                <label for="<?= $code ?>-cc-exp" class="label text-gray-700 text-sm">
                    <?= $escaper->escapeHtml(__('Card Expiration')) ?>
                </label>
                <input type="text"
                       inputmode="numeric"
                       title="<?= $escaper->escapeHtmlAttr(__('Card Expiration')) ?>"
                       class="block w-32 shadow-sm border-gray-300 rounded-md font-mono leading-normal tracking-wider transition"
                       id="<?= $code ?>-cc-exp"
                       name="payment[cc_exp]"
                       :value="payment.cc_exp"
                       @keyup="formatExpiration"
                       @change="validateExpiration"
                       value=""
                       autocomplete="cc-exp"
                       placeholder="MM / YYYY"
                       spellcheck="false"
                       maxlength="9"
                       required
                />
            </div>
            <div class="field required">
                <label for="<?= $code ?>-cc-cid"
                       class="label text-gray-700 text-sm"
                       x-text="getCcCidLabel"
                ></label>
                <input type="text"
                       inputmode="numeric"
                       title="<?= $escaper->escapeHtmlAttr(__('Card Verification Number')) ?>"
                       class="block w-16 shadow-sm border-gray-300 rounded-md font-mono leading-normal tracking-wider transition text-center"
                       id="<?= $code ?>-cc-cid"
                       name="payment[cc_cid]"
                       :value="payment.cc_cid"
                       @change="validateCvv"
                       value=""
                       autocomplete="cc-csc"
                       :placeholder="getCcCidPlaceholder"
                       spellcheck="false"
                       :minlength="getCcCidLength"
                       :maxlength="getCcCidLength"
                       required
                />
            </div>
        </div>
        <span class="text-red-600"
              id="payment-error-general"
              x-show="getErrorMessage"
              x-text="getErrorMessage"
        ></span>
        <?php if (!$formBlock->isGuestCheckout()): ?>
            <div x-show="showForm"
                 x-cloak
                 class="flex items-center gap-2 mt-2"
            >
                <?php if ((bool)$method->getConfigData('allow_unsaved')): ?>
                    <input type="checkbox"
                           title="<?= $escaper->escapeHtmlAttr(__('Save for next time')) ?>"
                           class="cursor-pointer"
                           id="<?= $code ?>-save"
                           name="payment[save]"
                           :value="payment.save"
                           @change="setSave"
                    />
                    <label for="<?= $code ?>-save"
                           class="label text-gray-700 text-sm cursor-pointer">
                        <?= $escaper->escapeHtml(__('Save for next time')) ?>
                    </label>
                <?php else: ?>
                    <p class="text-secondary mt-4 text-sm"><?= $escaper->escapeHtml(__('For your convenience, this data will be stored securely by our payment processor.')) ?></p>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>

    <?php if ($formBlock->hasVerification() && $method->getConfigData('require_ccv')): ?>
        <div class="field required"
             x-show="hideForm"
             x-cloak
        >
            <label for="<?= $code ?>-cc-cid-saved"
                   class="label text-gray-700 text-sm"
                   x-text="getCcCidLabel"
            >
                <?= $escaper->escapeHtml(__('CVV')) ?>
            </label>
            <input type="text"
                   inputmode="numeric"
                   title="<?= $escaper->escapeHtmlAttr(__('Card Verification Number')) ?>"
                   class="block w-16 shadow-sm border-gray-300 rounded-md font-mono leading-normal tracking-wider transition text-center"
                   id="<?= $code ?>-cc-cid-saved"
                   name="payment[cc_cid]"
                   :value="payment.cc_cid"
                   @change="validateCvv"
                   value=""
                   autocomplete="cc-csc"
                   :placeholder="getCcCidPlaceholder"
                   spellcheck="false"
                   :minlength="getCcCidLength"
                   :maxlength="getCcCidLength"
                   required
            />

            <?php if ($magewire->hasError('paymentCcCid')): ?>
                <span class="text-red-800" id="payment-cc-cid-error">
                    <?= $escaper->escapeHtml($magewire->getError('paymentCcCid')) ?>
                </span>
            <?php endif ?>
        </div>
    <?php endif; ?>

    <?= $block->getChildHtml(); ?>
</div>
