<?php declare(strict_types=1);
/**
 * Copyright © 2023-present ParadoxLabs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Need help? Try our knowledgebase and support system:
 *
 * @link https://support.paradoxlabs.com
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use ParadoxLabs\Authnetcim\Model\ConfigProvider;
use ParadoxLabs\AuthnetcimHyvaCheckout\Magewire\Payment\Authnetcim;
use ParadoxLabs\AuthnetcimHyvaCheckout\ViewModel\PaymentForm;

/** @var Template $block */
/** @var Authnetcim $magewire */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var PaymentForm $formViewModel */

$code           = $escaper->escapeHtmlAttr($block->getData('method_code'));
$formViewModel  = $viewModels->require(PaymentForm::class);
$formBlock      = $formViewModel->getFormBlock($code);
$method         = $formBlock->getMethod();
$image          = $formBlock->getBrandingImage();
?>
<div class="<?= /* @noEscape */ $code ?>"
     x-data="<?= /* @noEscape */ $code ?>PaymentForm"
     x-init="initForm"
     data-config='<?= $escaper->escapeJsQuote(json_encode($block->getConfig())) ?>'
>
    <?php if ($image): ?>
        <div class="flex justify-end mb-2">
            <img src="<?= $escaper->escapeUrl($image); ?>" alt="<?= $escaper->escapeHtmlAttr($method->getTitle()) ?>" />
        </div>
    <?php endif; ?>

    <?php if ($method->getConfigData('form_type') !== ConfigProvider::FORM_HOSTED): ?>
        <p class="message error my-8">
            <?= $escaper->escapeHtml(__('This payment method only supports Accept Hosted for Hyva Checkout. Please change the "Payment Form Type" to "Accept Hosted" in the payment method settings.')) ?>
        </p>
    <?php endif; ?>

    <div class="field required mb-2" x-show="showStoredCards" x-cloak>
        <label for="<?= /* @noEscape */ $code ?>-card-id" class="label text-gray-700 text-sm">
            <?= $escaper->escapeHtml(__('Payment Information')) ?>
        </label>
        <select id="<?= /* @noEscape */ $code ?>-card-id"
                class="block w-full shadow-sm border-gray-300 rounded-md"
                :value="selectedCard"
                @change="setSelectedCard"
        >
            <template x-for="storedCard in storedCards" :key="storedCard.hash">
                <option :value="storedCard.hash"
                        :data-type="storedCard.type"
                        :selected="isStoredCardSelected"
                        x-text="storedCard.label">
                </option>
            </template>
            <option value=''><?= $escaper->escapeHtml(__('Add new card')) ?></option>
        </select>

        <input type="text" class="hidden" autocomplete="cc-type" />
    </div>

    <div class="card p-0"
         x-show="showHostedForm"
         wire:ignore
    >
        <iframe src="about:blank" id="<?= /* @noEscape */ $code ?>_iframe" name="<?= /* @noEscape */ $code ?>_iframe" class="w-full" x-show="hideTermsNotice" x-cloak></iframe>
        <p x-show="showTermsNotice" x-cloak class="text-secondary p-4"><?= $escaper->escapeHtml(__('Please accept the %1 to complete payment.', __('Terms and Conditions'))) ?></p>
    </div>

    <?php if (!$formBlock->isGuestCheckout() && (bool)$method->getConfigData('allow_unsaved') === false): ?>
        <div x-show="showHostedForm" x-cloak>
            <p class="text-secondary mt-4 text-sm"><?= $escaper->escapeHtml(__('For your convenience, this data will be stored securely by our payment processor.')) ?></p>
        </div>
    <?php endif; ?>

    <?php if ($formBlock->hasVerification() && $method->getConfigData('require_ccv')): ?>
        <div class="field required"
             x-show="hideHostedForm"
             x-cloak
        >
            <label for="<?= /* @noEscape */ $code ?>-cc-cid"
                   class="label text-gray-700 text-sm"
            >
                <?= $escaper->escapeHtml(__('Card Verification Number')) ?>
            </label>
            <input type="text"
                   inputmode="numeric"
                   title="<?= $escaper->escapeHtmlAttr(__('Card Verification Number')) ?>"
                   class="block w-16 shadow-sm border-gray-300 rounded-md font-mono font-medium leading-normal tracking-wider transition text-center"
                   id="<?= /* @noEscape */ $code ?>-cc-cid"
                   name="payment[cc_cid]"
                   :value="payment.cc_cid"
                   @change="validateCvv"
                   value=""
                   autocomplete="cc-csc"
                   :placeholder="getCcCidPlaceholder"
                   spellcheck="false"
                   :minlength="getCcCidLength"
                   :maxlength="getCcCidLength"
                   required
            />
        </div>
    <?php endif; ?>

    <?= $block->getChildHtml(); ?>
</div>
